name: 12AMAuto Stop EC2

on:
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap jam 12 malam (00:00)

jobs:
  auto-stop-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto12AMStop EC2
        run: aws ec2 stop-instances --instance-ids ${{ secrets.INSTANCE_IDS }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.INSTANCE_REGION }}
