name: Auto Start/Stop EC2

on:
  push:
    branches:
      - main

jobs:
  auto-start-stop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start EC2
        run: aws ec2 start-instances --instance-ids ${{ secrets.INSTANCE_IDS }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.INSTANCE_REGION }}

      # Add steps to do other tasks as needed

      - name: Stop EC2
        run: aws ec2 stop-instances --instance-ids ${{ secrets.INTANCE_IDS }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.INSTANCE_REGION }}
