name: Auto Start/Stop EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (start or stop)'
        required: true
        default: 'start' # Default to start environment

jobs:
  start-ec2:
    environment:
      name: Start EC2
    runs-on: ubuntu-latest
    steps:
      - name: Start EC2
        run: aws ec2 start-instances --instance-ids ${{ secrets.INSTANCE_IDS }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.INSTANCE_REGION }}

  # Add steps to do other tasks as needed

  stop-ec2:
    needs: start-ec2
    environment:
      name: Stop EC2
    runs-on: ubuntu-latest
    steps:
      - name: Stop EC2
        run: aws ec2 stop-instances --instance-ids ${{ secrets.INSTANCE_IDS }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.INSTANCE_REGION }}
