name: Auto Start/Stop EC2

on:
  workflow_dispatch:

jobs:
  auto-start-stop:
    runs-on: ubuntu-latest

    environment:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.INSTANCE_REGION }}

    inputs:
      action:
        description: 'Action to perform (start or stop)'
        required: true
        default: 'start' # Default to start

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.INSTANCE_REGION }}
        if: ${{ github.event.inputs.action == 'start' }}

      - name: Run EC2 Action
        run: |
          if [ ${{ github.event.inputs.action }} == "start" ]; then
            aws ec2 start-instances --instance-ids ${{ secrets.INSTANCE_IDS }}
          elif [ ${{ github.event.inputs.action }} == "stop" ]; then
            aws ec2 stop-instances --instance-ids ${{ secrets.INSTANCE_IDS }}
          fi
        if: ${{ github.event.inputs.action == 'start' || github.event.inputs.action == 'stop' }}
